USE_YOLO_DEFAULT = True
YOLO_MODEL_NAME = "yolov8n.pt"

VEHICLE_CLASSES = {"car", "truck", "bus", "motorbike", "person"}

FRAME_WIDTH = 960
FRAME_SKIP = 0

MIN_CONTOUR_AREA = 1500
MIN_ASPECT_RATIO = 1.2
MAX_DISAPPEARED = 20
MAX_ASSOCIATION_DISTANCE = 70
